---
  - name: "PLAY 1 - PRINTING OUT IOS HOSTNAME AND NETWORK OS"
    hosts: "iosxe"
    connection: "network_cli"
    gather_facts: no
    tasks:

    - name: "TASK 1: PRINT DEBUG MAGIC VARIABLES FOR IOS"
      ansible.builtin.debug :
        msg: "The hostname is {{ inventory_hostname }} with a network os of {{ ansible_network_os }}"
