
---
  - name: "PLAY 1 - REMOVE CONFIG FROM DEMO"
    hosts: "iosxe"
    connection: "network_cli"
    ignore_errors: yes
    gather_facts: no
    tasks:
      - name: "TASK 1 - REMOVE CDP AND LLDP"
        cisco.ios.ios_config:
          lines:
              - "no cdp run"
              - "no lldp run"

      - name: "TASK 5 - REMOVE SHOW_OUTPUTS DIR IF EXISTS"
        ansible.builtin.file:
          path: "config"
          state: "absent"
        run_once: true


      - name: "TASK 3 - REMOVE INTERFACES"
        cisco.ios.ios_config:
          lines:
              - "no interface Loopback1337"
              - "no interface Loopback124"
              - "no interface Loopback125"
              - "no interface Loopback1450"

      - name: "TASK 4 - REMOVE SHOW_OUTPUTS DIR IF EXISTS"
        ansible.builtin.file:
          path: "show_outputs"
          state: "absent"
        run_once: true

      - name: "TASK 5 - REMOVE SHOW_OUTPUTS DIR IF EXISTS"
        ansible.builtin.file:
          path: "backup"
          state: "absent"
        run_once: true

      - name: "TASK 6 - REMOVE SNMP"
        cisco.ios.ios_config:
          lines:
              - "no snmp-server community cat8k_read_only ro"
              - "no snmp-server community cat8k_read_write rw"
              - "no snmp-server contact cat8k_lab_admin"
              - "no snmp-server location cat8k_rno"